services:

  db:
    image: mysql:8.4
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'meliplay'
      MYSQL_ROOT_PASSWORD: 'abc'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./meliplay.sql:/docker-entrypoint-initdb.d/meliplay.sql